### ISSUE TITLE
__declspec not available on Linux

### ISSUE THREAD

**Issue by Kadabash** [hilgenberg/cplot#29]
Trying to build on Linux, I encountered a `__declspec` outside of the `Windows` folder:

https://github.com/hilgenberg/cplot/blob/b3e873e6cfafad1fa4486fc4c6bacdecc08a2535/Engine/Parser/Simplifier/Pattern.cc#L200

This leads to a build failure on my machine.
(Naively) removing the `__declspec(noreturn)` part lets me build successfully. To my understanding, `__declspec` is only available with MSVC, though I could be wrong.

(My system: Ubuntu 16.04, G++ 5.4.0)

**Comment by hilgenberg** [comment]
Oops, thanks!
