### ISSUE TITLE
Windows - Visual Studio solution file fails to build (include error)

### ISSUE THREAD

**Issue by przet** [hilgenberg/cplot#30]
Using Visual Studio 2017, across all build configurations (Release, Debug 64 and 32 bit), there is a build error due to the boost math special functions not being found. I saw that in the CPlot project settings, the appropriate folder (cplot/Windows, which contains the boost folder copied over as per windows build instructions) is not included (verified via looking at the command line parameters in visual studio).

I have fixed this locally by adding the required include directory into all 4 configuration project settings, and they all build (and launch) fine now. I just need to set the paths to be relative now, not absolute (which I did for a quick check).

@hilgenberg have you experienced this, and are you happy for me to open a PR with the updated Visual Studio files?

**Comment by hilgenberg** [comment]
Hello Philippe,
sorry for the late reply. cplot/Windows/boost is already in the includes, so cplot\Windows\boost\boost\align.hpp should exist. Sounds like yours would be at cplot\Windows\boost\align.hpp (one less "boost" in the path). Sorry, the instructions really are ambiguous, I'll fix them next time I work on this.

**Comment by przet** [comment]
@hilgenberg no problems, thanks for getting back to me:) Yes you are right, I must have put the boost folder at the wrong level.
